<div class="jumbotron">
    <h1><?=$this->translate("Welcome to self check system")?></h1>
</div>

<div class="row align-items-center justify-content-center">

    <div class="col-md-4">
        <div class="card">
            <div class="card-block">
                <h3 class="card-title"><label for="library-card"><?=$this->translate("Enter your library card:")?></label></h3>
                <p class="card-text">
                    <form id="" >
                        <input id="library-card" name="library-card" type="text" />
                    </form>
                </p>
            </div>
        </div>
    </div>

</div>

