<div class="jumbotron pt-3 pb-2">
    <h2><?=$this->translate("Welcome to self check system")?></h2>
    <?php $mode = $this->mode; ?>
    <p><?=$this->translate("On this self check station you can")?>: 
    <ul>
        <li><?=$this->translate("Show information about your account")?></li>
    <?php
        if ($mode["checkin"]) {
    ?>
        <li><?=$this->translate("Return your checkouts")?></li>
    <?php
        }
        if ($mode["checkout"]) {
    ?>
        <li><?=$this->translate("Check out materials from library")?></li>
    <?php
        }
    ?>
    </ul>
    </p>
</div>

<div class="row justify-content-center">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title"><label for="library-card"><?=$this->translate("Enter your library card:")?></label></h3>
                <p class="card-text">
                    <form id="" class="form-inline" action="/patron/info" method="POST">
                        <div class="form-group">
                            <input id="library-card" name="library-card" class="form-control" type="text"  placeholder="<?=$this->translate("Your library card number")?>"/>
                        </div>
                        <button type="submit" class="btn btn-primary"><?=$this->translate("Submit")?></button>
                    </form>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <h3><?=$this->translate("Quick help")?></h3>
        <ol>
            <li><?=$this->translate("Use barcode scanner/RFID reader to insert identification number of your library card")?></li>
            <li><?=$this->translate("Scan barcodes of processed item")?></li>
            <li><?=$this->translate("Click (or tap) on Log out button to end work")?></li>
        </ol>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $("#library-card").focus();
    });
</script>
